In [19]:
import numpy as np #linear algebra
import pandas as pd #data processing
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score


# Read the CSV file
df = pd.read_csv('../data/raw/netflix_titles.csv', index_col =  0)

ModuleNotFoundError: No module named 'sklearn'

In [11]:
df.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [13]:
#Preprocess the data
df.fillna("", inplace=True)
df.head(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [14]:
#Esta es una forma de mostrarlo
df.loc["s3"]

type                                                      TV Show
title                                                   Ganglands
director                                          Julien Leclercq
cast            Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
country
date_added                                     September 24, 2021
release_year                                                 2021
rating                                                      TV-MA
duration                                                 1 Season
listed_in       Crime TV Shows, International TV Shows, TV Act...
description     To protect his family from a powerful drug lor...
Name: s3, dtype: object

In [15]:
#Así lo podemos mostrar como un dataframe
df.loc[["s1"]]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."

In [16]:
#podemos agregar mas de una fila de esta forma
df.loc[["s1","s5","s20"]]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
s20,TV Show,Jaguar,,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."

In [17]:
# podemos incluir solo las columnas que nos interesan de esta forma(incluiremos titulo, tipo y descripcion)
df.loc[["s1","s5","s20"], ["title","type","description"]]

,title,type,description
show_id,,,
s1,Dick Johnson Is Dead,Movie,"As her father nears the end of his life, filmm..."
s5,Kota Factory,TV Show,In a city of coaching centers known to train I...
s20,Jaguar,TV Show,"In the 1960s, a Holocaust survivor joins a gro..."

In [23]:
#Tambien podemos usar loc para seleccionar todas las filas, pero solo un numero especifico de columnas
df.loc[:, ["title","type","description"]]

,title,type,description
show_id,,,
s1,Dick Johnson Is Dead,Movie,"As her father nears the end of his life, filmm..."
s2,Blood & Water,TV Show,"After crossing paths at a party, a Cape Town t..."
s3,Ganglands,TV Show,To protect his family from a powerful drug lor...
s4,Jailbirds New Orleans,TV Show,"Feuds, flirtations and toilet talk go down amo..."
s5,Kota Factory,TV Show,In a city of coaching centers known to train I...
...,...,...,...
s8803,Zodiac,Movie,"A political cartoonist, a crime reporter and a..."
s8804,Zombie Dumb,TV Show,"While living alone in a spooky town, a young g..."
s8805,Zombieland,Movie,Looking to survive in a world taken over by zo...
s8806,Zoom,Movie,"Dragged from civilian life, a former superhero..."
s8807,Zubaan,Movie,A scrappy but poor boy worms his way into a ty...

In [24]:
#con iloc podemos seleccionar utilizando el indice
df.iloc[[0]]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [29]:
#podemos seleccionar multiples filas
df.iloc[[0,4,19],[1,0,10]]

,title,type,description
show_id,,,
s1,Dick Johnson Is Dead,Movie,"As her father nears the end of his life, filmm..."
s5,Kota Factory,TV Show,In a city of coaching centers known to train I...
s20,Jaguar,TV Show,"In the 1960s, a Holocaust survivor joins a gro..."

In [30]:
df.iloc[:,[1,0,10]]

,title,type,description
show_id,,,
s1,Dick Johnson Is Dead,Movie,"As her father nears the end of his life, filmm..."
s2,Blood & Water,TV Show,"After crossing paths at a party, a Cape Town t..."
s3,Ganglands,TV Show,To protect his family from a powerful drug lor...
s4,Jailbirds New Orleans,TV Show,"Feuds, flirtations and toilet talk go down amo..."
s5,Kota Factory,TV Show,In a city of coaching centers known to train I...
...,...,...,...
s8803,Zodiac,Movie,"A political cartoonist, a crime reporter and a..."
s8804,Zombie Dumb,TV Show,"While living alone in a spooky town, a young g..."
s8805,Zombieland,Movie,Looking to survive in a world taken over by zo...
s8806,Zoom,Movie,"Dragged from civilian life, a former superhero..."
s8807,Zubaan,Movie,A scrappy but poor boy worms his way into a ty...